{{- if and .Values.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kuberang-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kuberang
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: 
      - "*"
    resources: 
      - "nodes"
    verbs: 
      - "get"
      - "update"
      - "list"
{{- end -}}
